create table country (country_id bigint not null auto_increment, country_capital varchar(255), country_independence_date varchar(255), country_name varchar(255), iso_code varchar(255), primary key (country_id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), last_name varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('DO','República Dominicana','Santo Domingo','23/11/1986')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('CA','Canada','Ottawa','01/07/1867')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('EC','Ecuador','Quito','24/05/1822')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('HT','Haití','Puerto Príncipe','01/01/1804')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('VE','Venezuela','Caracas','05/07/1811')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('PY','Paraguay','Asunción','15/05/1811')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('JM','Jamaica','Kingston','06/08/1962')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('GT','Guatemala','Ciudad de Guatemala','15/09/1821')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('CR','Costa Rica','San José','15/07/1821')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('BO','Bolivia','Sucre','06/08/1825')
insert into user (email, name, last_name, password) values ('user@gmail.com', 'user', 'user_lastname', '1234')
insert into user (email, name, last_name, password) values ('user1@gmail.com', 'user1', 'user_lastname1', '1234')
create table country (country_id bigint not null auto_increment, country_capital varchar(255), country_independence_date varchar(255), country_name varchar(255), iso_code varchar(255), primary key (country_id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), last_name varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('DO','República Dominicana','Santo Domingo','23/11/1986')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('CA','Canada','Ottawa','01/07/1867')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('EC','Ecuador','Quito','24/05/1822')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('HT','Haití','Puerto Príncipe','01/01/1804')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('VE','Venezuela','Caracas','05/07/1811')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('PY','Paraguay','Asunción','15/05/1811')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('JM','Jamaica','Kingston','06/08/1962')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('GT','Guatemala','Ciudad de Guatemala','15/09/1821')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('CR','Costa Rica','San José','15/07/1821')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('BO','Bolivia','Sucre','06/08/1825')
insert into user (email, name, last_name, password) values ('user@gmail.com', 'user', 'user_lastname', '1234')
insert into user (email, name, last_name, password) values ('user1@gmail.com', 'user1', 'user_lastname1', '1234')
create table country (country_id bigint not null auto_increment, country_capital varchar(255), country_independence_date varchar(255), country_name varchar(255), iso_code varchar(255), primary key (country_id)) engine=InnoDB
create table user (id bigint not null auto_increment, email varchar(255), last_name varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('DO','República Dominicana','Santo Domingo','23/11/1986')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('CA','Canada','Ottawa','01/07/1867')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('EC','Ecuador','Quito','24/05/1822')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('HT','Haití','Puerto Príncipe','01/01/1804')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('VE','Venezuela','Caracas','05/07/1811')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('PY','Paraguay','Asunción','15/05/1811')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('JM','Jamaica','Kingston','06/08/1962')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('GT','Guatemala','Ciudad de Guatemala','15/09/1821')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('CR','Costa Rica','San José','15/07/1821')
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('BO','Bolivia','Sucre','06/08/1825')
insert into user (email, name, last_name, password) values ('user@gmail.com', 'user', 'user_lastname', '1234')
insert into user (email, name, last_name, password) values ('user1@gmail.com', 'user1', 'user_lastname1', '1234')
