version: '2'
services:
  mysql_container:
    image: mysql:latest
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: users_db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD:
